# Generated by Django 4.2.11 on 2024-05-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serviceid", models.CharField(max_length=30)),
                ("objectid", models.CharField(max_length=30)),
                ("transactionid", models.CharField(max_length=30)),
                ("transactiondate", models.DateField()),
                ("transactiontime", models.TimeField()),
                ("status", models.CharField(max_length=30)),
                ("message", models.CharField(max_length=30)),
                ("responsecode", models.BigIntegerField()),
            ],
        ),
    ]
